name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH
        env:
          KEY: ${{ secrets.CICD_KEY }}
        run: |
          echo "$KEY" | wc -c
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "$KEY" > ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@62.169.22.255 "echo OK"
